apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd 
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami 
    chart: kafka
    targetRevision: 26.1.2  
    helm:
      insecureSkipTLSVerify: true               
      valueFiles:
        - ../../values/kafka-values.yaml       
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
